[package]
name = "ppm"
version = "0.1.0"
edition = "2021"
description = "Lightweight user-mode Windows virtualization engine and multi-architecture portable package manager"
license = "MIT"
readme = "../../README.md"
keywords = [
    "portable",
    "virtualization",
    "windows",
    "detours",
    "package-manager"
]
categories = [
    "command-line-utilities",
    "os::windows-apis",
    "development-tools"
]

[build-dependencies]
cc = "1.2"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.13", features = ["blocking", "json"] }
indicatif = "0.18"
comfy-table = "8.0"
sevenz-rust = "0.6"
zip = "8.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yml = "0.0.13"
schemars = "1.0"
sha2 = "0.11"
hex = "0.4"
regex = "1.11"
tempfile = "3.18"
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_System_Environment",
    "Win32_System_SystemInformation",
    "Win32_System_LibraryLoader"
] }
